In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("Advertising_data.csv")
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
X = df.iloc[:,[2,3]].values
y = df.iloc[:,-1].values

###  Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=5)

### Feature Scaling

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit_transform(X_train)
sc.transform(X_test)

array([[ 0.77063564,  0.79680907],
       [-1.82054274, -1.28182329],
       [-0.18906005, -0.50975984],
       [-1.34069489, -1.1036548 ],
       [ 0.09884866,  0.23260886],
       [-0.09309048,  0.02474562],
       [-0.38099919, -0.77701257],
       [ 0.38675737,  0.17321936],
       [-0.28502962, -0.48006509],
       [ 0.38675737,  0.29199835],
       [-0.18906005,  1.65795676],
       [-1.24472532,  0.61864058],
       [-0.86084704,  0.41077735],
       [-0.6689079 , -0.09403337],
       [-0.28502962, -0.65823358],
       [-1.82054274, -1.31151803],
       [-0.28502962,  2.31124122],
       [ 0.19481823, -0.12372812],
       [-1.14875575,  0.35138785],
       [-0.09309048,  0.17321936],
       [ 0.96257478,  1.47978827],
       [ 0.09884866,  0.11382987],
       [ 2.11420962, -0.80670732],
       [ 0.2907878 ,  0.08413512],
       [ 0.67466608, -0.71762308],
       [-0.76487747, -1.60846551],
       [ 0.19481823, -0.3612861 ],
       [ 1.92227048, -0.92548631],
       [ 1.15451392,

### Fitting Kernel SVM to the Training set

In [6]:
from sklearn.svm import SVC
svc_clf = SVC()
svc_clf.fit(X_train,y_train)

SVC()

### Predicting the Test set results

In [7]:
y_pred = svc_clf.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int64)

### Finding the Confusion Matrix and Accuracy

In [8]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test,y_pred)
asc = accuracy_score(y_test,y_pred)
print(cm)
print(asc)

[[64  2]
 [16 18]]
0.82


### Applying Grid Search to find the best model and the best parameters

In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = [
    {"C":[1,10],"kernel":["linear"]},
    {"C":[1,10],"kernel":["rbf"],"gamma":[0.5,0.6,0.7,0.8,0.9]}
]

gscv = GridSearchCV(
    estimator = svc_clf,
    param_grid = parameters,
    scoring = "accuracy",
    cv = 5,
    n_jobs = -1
)
gscv.fit(X_train,y_train)

In [ ]:
accuracy = gscv.best_scores
accuracy

In [ ]:
gscv.best_params

In [ ]:
svc_clf = SVC(kernel = "rbf",gamma = )