### digits dataset from sklearn

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
import warnings
warnings.filterwarnings("ignore")
from sklearn.datasets import load_digits

digits = load_digits()

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9648148148148148

In [19]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9851851851851852

In [24]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9722222222222222

In [25]:
dc = DecisionTreeClassifier()
dc.fit(X_train,y_train)
dc.score(X_test,y_test)

0.8666666666666667

### KFold cross validation

In [20]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [23]:
for train_index ,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [26]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [29]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=3)
skf

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [37]:
scores_l = []
scores_svm = []
scores_dc = []
scores_rf = []

for train_index, test_index in skf.split(digits.data,digits.target):
    X_train,X_test,y_train,y_test = digits.data[train_index],digits.data[test_index], \
                                    digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_dc.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))

In [38]:
for train_index, test_index in skf.split(digits.data,digits.target):
    #print(train_index,test_index)
    print(len(train_index))
    print(len(test_index))

1198
599
1198
599
1198
599


In [39]:
scores_l

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [40]:
scores_svm

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [41]:
scores_dc

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [42]:
scores_rf 

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

### cross_val_score function

In [45]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3)

array([0.92153589, 0.94156928, 0.91652755])

In [46]:
from sklearn.model_selection import cross_val_score
cross_val_score(DecisionTreeClassifier(),digits.data,digits.target,cv=3)

array([0.73789649, 0.80634391, 0.76961603])

In [47]:
cross_val_score(SVC(),digits.data,digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [48]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=3)

array([0.94156928, 0.96160267, 0.92320534])

### Parameter tunning using k fold cross validation

In [49]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8758969584109251

In [50]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9437895716945995

In [51]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9421042830540036

In [52]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9437926753569211